/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'sergei' at '14/05/16 7:46 AM' with Gradle 2.13
 *
 * @author sergei, @date 14/05/16 7:46 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
